[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "seedplan"
version = "0.1.0"
description = "SeedPlan Backend"
requires-python = ">=3.11"

[tool.setuptools]
packages = ["models", "schemas", "auth", "database"] 